---
# Deployment parameters.
# The deployment process is divided into various stages.

# Deploy local Aptos.
deploy_aptos: true
deploy_databases: true
deploy_madara: True
deploy_madara_explorer: True

args:
  # Suffix appended to service names.
  # Note: It should be a string.
  deployment_suffix: "-001"

  # The global log level that all components of the stack should log at.
  # Valid values are "error", "warn", "info", "debug", and "trace".
  global_log_level: info

  # Additional services to run alongside the network.
  # Options:
  # - prometheus_grafana
  additional_services: ["prometheus_grafana"]

  aptos:
    image: sotazklabs/aptos-tools:mainnet
    rpc_port: 8080

  madara:
    image: sotazklabs/madara:latest
    rpc_port: 9944
    gateway_port: 8080

  madara_explorer:
    image: sotazklabs/stark_compass_explorer:v0.2.38
    port: 4000

  madara_orchestrator:
    image: sotazklabs/madara-orchestrator:latest
    port: 3000

  localstack:
    image: localstack/localstack:latest
    port: 4566
    default_region: us-east-1
    aws_access_key_id: test
    aws_secret_access_key: test

  sqs-admin-ui:
    image: akilamaxi/sqs-admin-ui:v1
    port: 8081

  pathfinder:
    image: sotazklabs/pathfinder:latest
    port: 9545