---
# Deployment parameters.
# The deployment process is divided into various stages.

# Deploy local Aptos.
deploy_aptos: True
deploy_databases: True
deploy_madara: True
deploy_madara_explorer: True
deploy_contracts: True

args:
  # Suffix appended to service names.
  # Note: It should be a string.
  deployment_suffix: "-001"

  # The global log level that all components of the stack should log at.
  # Valid values are "error", "warn", "info", "debug", and "trace".
  global_log_level: info

  # Additional services to run alongside the network.
  # Options:
  # - prometheus_grafana
  additional_services: ["prometheus_grafana"]

  aptos:
    image: sotazklabs/aptos-tools:mainnet
    rpc_port: 8080

  madara:
    image: sotazklabs/madara:latest
    rpc_port: 9944

  madara_explorer:
    image: sotazklabs/stark_compass_explorer:v0.2.38
    rpc_port: 4000

  jayce:
    image: sotazklabs/jayce:latest
    config_file: ../static_files/jayce/deploy-contracts.toml
    output_file_name: deploy-output.json
    contracts:
      - ../contracts/navori/libs
      - ../contracts/navori/cpu-2
      - ../contracts/navori/cpu
      - ../contracts/navori/verifier
      - ../contracts/ionia
